config/routes.rb
Rails.application.routes.draw do

  root to: 'dashing#dashboard'
  get 'dashing/dashboard'
  get 'billing_sites/:id/predictions' => 'billing_sites#show_predict_usage', as: :show_predictions_billing_site
  get 'billing_sites/:id/usage' => 'billing_sites#show_usage', as: :show_usage_billing_site
  post 'billing_sites/:id/usage' => 'billing_sites#show_usage'
  resources :ftp_servers


  # nested resources for testing purpose
  scope shallow_prefix: "billing_site" do
    resources :billing_sites do
      resources :retail_plans, shallow: true
    end
  end

#  resources :billing_sites

  resources :sites
  devise_for :users, controllers: { registrations: "users/registrations" }
  get 'users/import' => 'users#upload_nem12'
  post 'users/import' => 'users#import_nem12'
  # user's show page
  get 'users/:id' => 'users#show', as: 'user', constraints: { id: /\d+/ }

  # resources :users, only: [:show],
  get 'users/profile' => 'users#show'

  resources :meters, except: [:new, :index, :show, :edit]

  # If no route matches for show, index, edit page
  get '/meters' => 'application#redirect_user'
  get '/meters/:id' => 'application#redirect_user'
  get '/meters/:id/edit' => 'application#redirect_user'

  # resources :retail_plans do
  #   collection do
  #     get :edit
  #   end
  # end

  resources :invoices do
    collection do
      get :predictNew
      post :select_date_period
      post :predict, to: "invoices#create_predicted_invoice"
      get :generateNew
      post :generate, to: "invoices#create_generated_invoice"
      get :import_invoice
      post :import, to: "invoices#create_imported_invoice"
      post :compare
    end
  end

  get 'meter_records/truncate' => 'meter_records#truncate'
  get 'meter_records/import' => 'meter_records#import_nem12'
  get 'meter_records/single_usage' => 'meter_records#single_usage'
  get 'meter_records/multiple_usage' => 'meter_records#multiple_usage'
  get 'meter_records/single_predicted_usage' => 'meter_records#single_predicted_usage'
  get 'meter_records/multiple_predicted_usage' => 'meter_records#multiple_predicted_usage'

  get 'meter_aggregations/truncate' => 'meter_aggregations#truncate'

  resources :meter_records, :meter_aggregations

  # duplicated resources
  # resources :meters

  post '/billing_sites/:id' => 'billing_sites#show'

end

app/models/billing_site.rb
class BillingSite < ActiveRecord::Base

  belongs_to :site
  has_many :meters, dependent: :destroy
  has_many :retail_plans, dependent: :destroy
  has_many :invoices, through: :retail_plans

  #Generate a new invoice based on the updated usage data
  def self.update_generated_invoice meters, date_ranges
    
    #find all metering_charges of imported invoice in the database
    #because the charge_attributes of metering_charge have a list of relevant meters 
    concrete_charge_metering = []
    ConcreteCharge.all.each do |temp|
      charge_attribute = eval temp[:charge_attributes]
      if charge_attribute[:name].eql?("Metering Charge") && temp[:invoice_type].eql?("ImportedInvoice")
      concrete_charge_metering.push temp
      end
    end

    if !concrete_charge_metering.empty?
      #find relevant metering_charge with the meters
      concrete_charge_result = []
      concrete_charge_metering.each do |mcharge|
        meter_array = eval mcharge[:charge_attributes]
        meter_array = meter_array[:meters]
        meters.each do |meter|
          if !concrete_charge_result.include?(mcharge) && meter_array.include?(meter[:serial])
          concrete_charge_result.push mcharge
          end
        end
      end
      
      if !concrete_charge_result.empty?
        #find imported invoice with date period
        imported_invoice_result = []
        concrete_charge_result.each do |ccharge|
          date_ranges.each do |date_period|
            imported_invoice_temp = Invoice.find(ccharge[:invoice_id])
            if !imported_invoice_result.include?(imported_invoice_temp) &&
              (date_period[:start_date]<imported_invoice_temp[:end_date]||
                imported_invoice_temp[:start_date]<date_period[:end_date])
              imported_invoice_result.push imported_invoice_temp
            end
          end
        end
        
        if !imported_invoice_result.empty?
        #update the generated invoice
        imported_invoice_result.each do |invoice|
          result = {}
          result["id"] = invoice[:actable_id]
          result["start_date"] = invoice[:start_date]
          result["end_date"] = invoice[:end_date]
          result["issue_date"] = invoice[:issue_date]
          result["distribution_loss_factor"] = invoice[:distribution_loss_factor]
          result["marginal_loss_factor"] = invoice[:marginal_loss_factor]
          result["total"] = invoice[:total]
          result["retail_plan_id"] = invoice[:retail_plan_id]
          new_generated_invoice = GeneratedInvoice.new(result)
          new_generated_invoice.save
        end
        else
          logger.debug "No relevant imported invoice in the system"
        end
      else
        logger.debug "No relevant metering charge in the system"
      end
    else
      logger.debug "No metering charge in the system"
    end
  end
end

app/controllers/billing_sites_controller.rb
class BillingSitesController < ApplicationController
  before_action :set_billing_site, only: [:show, :edit, :update, :destroy, :show_predict_usage, :show_usage]

  # GET /billing_sites
  # GET /billing_sites.json
  def index
    @billing_sites = BillingSite.all.order(:id)

  end


  # GET /billing_sites/1/predictions
  def show_predict_usage
    # get the predicted electricity invoice
    start_date = Date.today
    end_date = Date.new(start_date.next_year.year,6,30) if start_date.month < 7
    end_date = Date.new(start_date.next_year.next_year.year, 6, 30) if start_date.month >= 7
    # get the meters belongs to the billing_site
    meters = @billing_site.meters
    # get the daily time periods from the retail plan
    daily_time_periods = RetailPlan.dailyTimePeriods meters
    puts daily_time_periods
    # create date_range input
    date_ranges = generate_date_ranges(start_date, end_date, 'Daily')
    dr = [{:start_date => start_date, :end_date => end_date}]
    usages = Meter.detailed_predicted_usage_by_time(dr, daily_time_periods, meters.to_a)
    # puts Benchmark.measure {format_converter usages, 'line', 'Daily'}
    predict_format_converter usages[0]
    # get the predicted invoices
    @predict_invoices = Invoice.get_prediction_invoice @billing_site.id
  end


  # GET /billing_sites/1/usage
  def show_usage
    query = params
    # Default data
    @start_date = Date.today.last_month
    @end_date = Date.today
    @interval = 'Daily'
    @type = 'line'
    #update the query
    if not query[:start_date].nil?
      @start_date = Date.parse(query[:start_date])
      @end_date = Date.parse(query[:end_date])
      @interval = query[:interval]
      @type = query[:type]
    end
    # get the meters belongs to the billing_site
    meters = @billing_site.meters

    # get the daily time periods from the retail plan
    daily_time_periods = RetailPlan.dailyTimePeriods meters
    puts daily_time_periods

    # create date_range input
    date_ranges = generate_date_ranges(@start_date, @end_date, @interval)
    # get the usage data
    usages = Meter.usage_by_time(date_ranges, daily_time_periods, meters.to_a)

    # convert the data format which can be used in javascript
    # format_converter usages[0], @type
    puts usages
    format_converter usages, daily_time_periods, @interval
  end


  # GET /billing_sites/1
  # GET /billing_sites/1.json
  def show
    # default dates
    start_date = Date.today - 1.year
    end_date = Date.today
    if (to = isDate params[:dateTo])
      if (from = isDate params[:dateFrom])
        #only change if both are good dates
        if from < to
          start_date = from
          end_date = to
        end
      end
    end
    @start_date = start_date
    @end_date = end_date
    @billing_site = set_billing_site
    @meters = @billing_site.meters.order(:id)
    @retail_plans = @billing_site.retail_plans.order(:id)
    @invoices = []

    # select from the associated Imported invoices those between start and end date
    importedInvoices = @billing_site.invoices(true).where(actable_type: ImportedInvoice,
                                                     start_date: start_date..end_date)

    #if there are imported invoices in system find their generated ones
    if !importedInvoices.blank?
      importedInvoices.each do |importedInvoice|
        generatedInvoices = @billing_site.invoices(true).where(actable_type: GeneratedInvoice,
                                                          start_date: importedInvoice.start_date,
                                                          end_date: importedInvoice.end_date)
        invoiceHash = {}

        invoiceHash[:Imported] = importedInvoice
        # process generated invoices, add values to hash
        generatedValues = []
        if !generatedInvoices.blank?
          generatedInvoices.each do |generatedInvoice|
            hash = {}
            hash[:id] = generatedInvoice.id

            # float needed for frontend
            hash[:total] = generatedInvoice.total.to_f
            generatedValues.push([generatedInvoice.created_at, hash])
          end
          invoiceHash[:GeneratedValues] = generatedValues
        else
          invoiceHash[:GeneratedValues] = []
        end
        @invoices.push(invoiceHash)
      end
    else
      @invoices =[]
    end
  end

  # GET /billing_sites/new
  def new
    @billing_site = BillingSite.new
  end


  # GET /billing_sites/1/edit
  def edit
  end


  # POST /billing_sites
  # POST /billing_sites.json
  def create
    @billing_site = BillingSite.new(billing_site_params)
    @bs = @billing_site.site_id
    @site = Site.find_by(:id => @bs)
    @all_billing_site = BillingSite.where(:site_id => @bs)
    count = 0

    #No two Billing site in same site shall have similar names
    @all_billing_site.each do |value|
      if value.name  == @billing_site.name
        count+=1
      end
    end
    respond_to do |format|
      if !@billing_site.name.blank?
        if count == 0
          if @billing_site.save
            format.html { redirect_to @billing_site, notice: 'Billing site was successfully created.' }
            format.json { render :show, status: :created, location: @billing_site }
          else
            format.html { render :new }
            format.json { render json: @billing_site.errors, status: :unprocessable_entity }
          end
        else
          format.html { redirect_to @site , alert: "Another Billing Site exists with the same name. Please give a new name" }
          format.json { render json: @billing_site.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to @site , alert: "Billing Site name cannot by empty. Try again" }
        format.json { render json: @billing_site.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /billing_sites/1
  # PATCH/PUT /billing_sites/1.json
  def update
    respond_to do |format|
      if @billing_site.update(billing_site_params)
        format.html { redirect_to @billing_site, notice: 'Billing site was successfully updated.' }
        format.json { render :show, status: :ok, location: @billing_site }
      else
        format.html { render :edit }
        format.json { render json: @billing_site.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /billing_sites/1
  # DELETE /billing_sites/1.json
  def destroy
    site = @billing_site.site_id
    @billing_site.destroy
    respond_to do |format|
      # format.html { redirect_to billing_sites_url, notice: 'Billing site was successfully destroyed.' }
      format.html { redirect_to site_path(site), notice: 'Billing site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  ##
  # Convert the usage into the format what the google chart can be used
  #
  # ==== Attributes
  #
  # * +usages+ - The detail electricity usages of specific date period
  # * +daily_time_periods+ - the date range with start date and end date
  # * +interval+ - The interval of the date e.g 'Daily', 'Monthly', 'Quarterly'
  #
  # ==== Examples
  #
  # format_converter {:start_time, :end_time, ...}, 'line', 'Daily'
  #
  def format_converter (usages, daily_time_periods, interval)
    @date = [] # Date List
    @total = [] # Total usage List
    @lines = [] # Label list
    @labels = [] # Lines list, each element is the list of one line usage
    @table_array = [] # table structure
    @table_array.append("date[i]")  #["date[i]", "total[i]", "line[0][i]", "line[1][i]"]
    @table_array.append('total[i]')
    daily_time_periods.each_with_index do |dtp, index|
      @name ="lines[#{index.to_s}][i]"
      @table_array.append(@name)
      @lines.append([]) #[[], []]
      @labels.append(dtp[:label])
    end
    usages.each_with_index do |usage, usage_index|

      @date.append(usage[:start_date].to_s) if interval == 'Daily' #[2012-1-1, 2012-2-2]
      @date.append(usage[:start_date].strftime('%B')) if interval == 'Monthly'
      @date.append("#{usage[:start_date].beginning_of_quarter.strftime("%B")}
        --#{usage[:start_date].end_of_quarter.strftime('%B')}") if interval == 'Quarterly'
      @total.append(usage[:usage]) #[total1, total2]

      usage[:daily_time_periods].each_with_index do |period, index|
        @lines[index].append(period[:usage]) #[[peak-usage], [off-peak-usage]]
      end if usage[:daily_time_periods]
      # if daily_time_periods is empty, add nil for each lines data
      daily_time_periods.each_with_index do |period, index|
        @lines[index].append(nil)
      end if usage[:daily_time_periods] == []
    end
  end


  def get_prediction_invoice billing_site_id
    @predicted_invoices = []
    billing_site =BillingSite.find(billing_site_id)
    retail_plan = billing_site.retail_plans.last
    invoice = retail_plan.invoices.where(actable_type: ImportedInvoice).last
    @imported_invoice = invoice.specific
    # @file_name = ImportedInvoice.find(@imported_invoice.actable_id).file
    @predictable_billing_periods = retail_plan.predictable_billing_periods
    @predictable_billing_periods.each do |predictable_billing_period|
      #Based on the selection of imported invoice from the user
      attributes = Marshal.load( Marshal.dump(@imported_invoice.attributes))
      attributes["start_date"] = predictable_billing_period[:start_date]
      attributes["end_date"] = predictable_billing_period[:end_date]
      @predicted_invoice = PredictedInvoice.new(attributes.except!("file"))
      if @predicted_invoice.save
            logger.info "predicted_invoices for '"+@imported_invoice.specific.file+"' are successfully created"
            @predicted_invoices << @predicted_invoice
      else

app/helpers/billing_sites_helper.rb
module BillingSitesHelper
end

app/views/billing_sites/_form.html.erb
<div class="modal-body">
<%= simple_form_for(@billing_site) do |f| %>
  <% if @billing_site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@billing_site.errors.count, "error") %> prohibited this billing_site from being saved:</h2>

      <ul>
      <% @billing_site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <!-- <%# f.label :name %><br> -->
    <%# f.text_field :name %>
    <%= f.input :name, label_html: { style: 'color: black' } %>
  </div>
  <div class="field">
    <%= f.input :created, label_html: { style: 'color: black' } %>
  </div>
  <div class="field">
    <!-- changed by Charlene -->
    <%= f.hidden_field :site_id, :value=>params[:site_id] || site_id %>
  </div>
</div>
  <!-- <div class="field">
     <%# f.hidden_field :created, :value =>Time.now%>
  </div> -->
  <div class="modal-footer">
    <div class="actions">
      <%= f.submit :class =>"btn btn-primary" %>
      <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button> -->
    </div>
  </div>
<% end %>

app/views/billing_sites/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">Editing Billing Site: <%= @billing_site.name %></h1>
    <%= link_to '< Back', @billing_site %>
  </div>
</div>

<%= render 'form' %>

<% if false %>
<%= link_to 'Show', @billing_site %> |
<%= link_to 'Back', @billing_site %>
<% end %>




app/views/billing_sites/index.html.erb
<!-- changed by Charlene -->
<div class="row">
  <div class="col-md-12">
    <p id="notice"><%= notice %></p>
    <h1 class="page-header">Listing Billing Sites</h1>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Site</th>
      <th>Created</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @billing_sites.each do |billing_site| %>
      <tr>
        <td><%= billing_site.name %></td>
        <td><%= billing_site.site_id %></td>
        <td><%= billing_site.created %></td>
        <td><%= link_to 'Show', billing_site %></td>
        <td><%= link_to 'Edit', edit_billing_site_path(billing_site) %></td>
        <td><%= link_to 'Destroy', billing_site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Billing site', new_billing_site_path %>

app/views/billing_sites/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">New Billing Site</h1>
  </div>
</div>

<%= render 'form' %>



app/views/billing_sites/show_predict_usage.html.erb
<script type="text/javascript">
    var table = [];
    var nil = null;
    var date = <%= raw @date %>;
    var total = <%= @total %>;
    var lines = [];
    var labels = <%=raw @labels%>;
    for (i = 0; i < labels.length; i++) {
        lines.push([]);
        lines = <%= @lines %>;
    }

    for (i = 0; i < date.length; i++) {
        table.push(<%= "["+@table_array.join(',')+"]" %>);

    }
    google.load('visualization', '1', {packages: ['corechart', 'line']});
    google.setOnLoadCallback(drawCrosshairs);

    function drawCrosshairs() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Date');
        data.addColumn('number', 'Total Usage');
        for (i = 0; i < labels.length; i++) {
            data.addColumn('number', labels[i]);
        }

        data.addRows(table);

        var options = {
            chart: {
                title: 'Electricity Prediction',
                subtitle: 'by STEAM'
            },
            vAxis: {format: 'decimal'}
        };

        var chart = new google.charts.Line(document.getElementById('line_chart'));

        chart.draw(data, google.charts.Line.convertOptions(options));
        chart.setSelection([
            {row: 38, column: 1}
        ]);

    }
</script>


<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1>Usage Prediction</h1>
    </div>
  </div>

  <div class="col-md-12">
    <div id="line_chart" style="width: 900px; height: 500px"></div>
  </div>

</div>
<div class="row">
  <div class="col-md-12">
    <div class="col-md-12">
      <div class="page-header">
        <h1>Invoice Prediction</h1>
      </div>
    </div>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Invoice ID</th>
        <th>Start time</th>
        <th>End time</th>
        <th>Cost</th>
      </tr>
      </thead>

      <tbody>
      <% @predict_invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.id %></td>
            <td><%= invoice.start_date %></td>
            <td><%= invoice.end_date %></td>
            <td><%= invoice.total %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/billing_sites/show_usage.html.erb
<script type="text/javascript">
    var table = [];
    var nil = null;
    var date = <%=raw @date %>;
    var total = <%= @total %>;
    var lines = [];
    var labels = <%=raw @labels%>;
    var lines = <%= @lines %>;

    for (i = 0; i < date.length; i++) {
        table.push(<%= "["+@table_array.join(',')+"]" %>);
    }

    google.load('visualization', '1', {packages: ['corechart', 'line']});
    google.load('visualization', '1', {packages: ['corechart', 'bar']});
    google.setOnLoadCallback(drawLineChart);
    google.setOnLoadCallback(drawBarChart);
    function drawLineChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Time');
        data.addColumn('number', 'Total Usage');
        for (i = 0; i < labels.length; i++) {
            data.addColumn('number', labels[i]);
        }

        data.addRows(table);

        var options = {
            chart: {
                title: 'Electricity Usage',
                subtitle: 'by STEAM'
            },
            vAxis: {format: 'decimal'}
        };

        var chart = new google.charts.Line(document.getElementById('line_chart'));

        chart.draw(data, google.charts.Line.convertOptions(options));
        chart.setSelection([
            {row: 38, column: 1}
        ]);

    }

    function drawBarChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Time');
        data.addColumn('number', 'Total')
        for (i = 0; i < labels.length; i++) {
            data.addColumn('number', labels[i]);
        }
        data.addRows(table);

        var options = {
            chart: {
                title: 'Electricity Usage',
                subtitle: ''
            },
            bars: 'vertical',
            vAxis: {format: 'decimal'}
        };

        var chart = new google.charts.Bar(document.getElementById('bar_chart'));
        chart.draw(data, google.charts.Bar.convertOptions(options));
    }
</script>

<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <div class="pull-right">
        <!--This the button on the right of the header-->
      </div>
      <h1>Displaying Electricity Usage</h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= bootstrap_form_tag layout: :inline do |f| %>
        <strong>Start
          Date:</strong> <%= f.text_field :start_date, hide_label: true, class: 'datepicker', value: @start_date %>
        <strong>End
          Date:</strong> <%= f.text_field :end_date, hide_label: true, class: 'datepicker', value: @end_date %>
        <%= f.select :interval, ["Daily", "Monthly", "Quarterly"], {label: "Interval:", selected: @interval}, {data: {behavior: "datepicker"}} %>
        <%= f.form_group :type, label: {text: "As: "} do %>
            <%= f.radio_button :type, 'line', label: "Line", checked: @type.eql?('line') %>
            <%= f.radio_button :type, 'bar', label: "Bar", checked: @type.eql?('bar') %>
        <% end %>
        <%= f.submit 'Update', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @type == 'line' %>
        <div id="line_chart" style="width: 900px; height: 500px; margin: 20px"></div>
    <% else %>
        <div id="bar_chart" style="width: 900px; height: 500px; margin: 20px"></div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.datepicker').datepicker({format: "yyyy-mm-dd"});
    });
</script>