config/routes.rb
Rails.application.routes.draw do

  root to: 'dashing#dashboard'
  get 'dashing/dashboard'
  get 'billing_sites/:id/predictions' => 'billing_sites#show_predict_usage', as: :show_predictions_billing_site
  get 'billing_sites/:id/usage' => 'billing_sites#show_usage', as: :show_usage_billing_site
  post 'billing_sites/:id/usage' => 'billing_sites#show_usage'
  resources :ftp_servers


  # nested resources for testing purpose
  scope shallow_prefix: "billing_site" do
    resources :billing_sites do
      resources :retail_plans, shallow: true
    end
  end

#  resources :billing_sites

  resources :sites
  devise_for :users, controllers: { registrations: "users/registrations" }
  get 'users/import' => 'users#upload_nem12'
  post 'users/import' => 'users#import_nem12'
  # user's show page
  get 'users/:id' => 'users#show', as: 'user', constraints: { id: /\d+/ }

  # resources :users, only: [:show],
  get 'users/profile' => 'users#show'

  resources :meters, except: [:new, :index, :show, :edit]

  # If no route matches for show, index, edit page
  get '/meters' => 'application#redirect_user'
  get '/meters/:id' => 'application#redirect_user'
  get '/meters/:id/edit' => 'application#redirect_user'

  # resources :retail_plans do
  #   collection do
  #     get :edit
  #   end
  # end

  resources :invoices do
    collection do
      get :predictNew
      post :select_date_period
      post :predict, to: "invoices#create_predicted_invoice"
      get :generateNew
      post :generate, to: "invoices#create_generated_invoice"
      get :import_invoice
      post :import, to: "invoices#create_imported_invoice"
      post :compare
    end
  end

  get 'meter_records/truncate' => 'meter_records#truncate'
  get 'meter_records/import' => 'meter_records#import_nem12'
  get 'meter_records/single_usage' => 'meter_records#single_usage'
  get 'meter_records/multiple_usage' => 'meter_records#multiple_usage'
  get 'meter_records/single_predicted_usage' => 'meter_records#single_predicted_usage'
  get 'meter_records/multiple_predicted_usage' => 'meter_records#multiple_predicted_usage'

  get 'meter_aggregations/truncate' => 'meter_aggregations#truncate'

  resources :meter_records, :meter_aggregations

  # duplicated resources
  # resources :meters

  post '/billing_sites/:id' => 'billing_sites#show'

end

app/controllers/meter_records_controller.rb
class MeterRecordsController < ApplicationController

  before_action :set_meter_record, only: [:show, :edit, :update, :destroy]


  def get_meters
    meters = []

     meters.push Meter.find_by_serial('8056402')
     meters.push Meter.find_by_serial('2021')
    # meters.push Meter.find_by_serial('2022')
    # meters.push Meter.find_by_serial('2023')
    # meters.push Meter.find_by_serial('2024')
     meters.push Meter.find_by_serial('2025')
    return meters
  end


  def get_date_ranges

    return [
      {
        :start_date => '2010-01-02'.to_date,
        :end_date => '2011-01-01'.to_date,
      },
    ]


    return [
      {
        :start_date => '2001-07-01'.to_date,
        :end_date => '2002-07-06'.to_date,
      },
      # {
      #   :start_date => '2001-06-30'.to_date,
      #   :end_date => '2002-07-6'.to_date,
      # }
    ]
  end

  def get_dtps

    return [
        {
          :label => 'Retail Peak',
          :start_time => Time.utc(2001, 1, 1, 7, 0, 0),
          :end_time => Time.utc(2001, 1, 1, 20, 0, 0),
        },
        {
          :label => 'Network Peak',
          :start_time => Time.utc(2001, 1, 1, 7, 0, 0),
          :end_time => Time.utc(2001, 1, 1, 20, 0, 0),
        },
        {
          :label => 'Retail Off-Peak',
          :start_time => Time.utc(2001, 1, 1, 22, 0, 0),
          :end_time => Time.utc(2001, 1, 1, 7, 0, 0),
        },
        {
          :label => 'Network Off-Peak',
          :start_time => Time.utc(2001, 1, 1, 22, 0, 0),
          :end_time => Time.utc(2001, 1, 1, 7, 0, 0),
        }
      ]



    return [
      {
        :label => "Peak",
        :start_time => Time.new(2000, 1, 1, 7, 0),
        :end_time => Time.new(2000, 1, 1, 19, 0),
      },
      {
        :label => "Shoulder",
        :start_time => Time.new(2000, 1, 1, 19, 0),
        :end_time => Time.new(2000, 1, 1, 22, 0),
      },
      {
        :label => "Off-Peak",
        :start_time => Time.new(2000, 1, 1, 22, 0),
        :end_time => Time.new(2000, 1, 1, 7, 0),
      },
    ]
  end

# Calls the static class method Meter.import
  def import_nem12

    truncate_records
    truncate_aggregations

    meters = get_meters
    #directory = "homes/reuben/test"
    #directory = "homes/reuben/09-07-2015"
    #directory = "homes/reuben/1"
    #directory = "homes/testdata"
    directory = "homes/reuben/clariti"
    result = Meter.import_nem12(directory, meters)
    logger.info result
    redirect_to action: 'index'
  end

# Calls the Meter.usage static class method
  def multiple_usage
    date_ranges = get_date_ranges
    meters = get_meters
    dtps = get_dtps

    #MeterAggregation.aggregate_missing_data date_ranges, dtps, meters

    #dtps = []

    #usages = Meter.usage_by_meter date_ranges, dtps, meters
    #usages = Meter.detailed_usage_by_meter date_ranges, dtps, meters
    #usages = Meter.usage_by_time date_ranges, dtps, meters
    usages = {}

    t = Benchmark.measure {
      usages = Meter.detailed_usage_by_time date_ranges, dtps, meters
    }
    logger.info "Time taken => #{t}"
    # usages[:query_time] = t
    render :json => usages

    #redirect_to action: 'index'
  end

  def multiple_predicted_usage
    date_ranges = get_date_ranges
    meters = get_meters
    dtps = Meter.get_daily_time_periods meters

    #usages = Meter.predicted_usage_by_meter date_ranges, dtps, meters
    #usages = Meter.predicted_usage_by_time date_ranges, dtps, meters
    usages = Meter.detailed_predicted_usage_by_meter date_ranges, dtps, meters
    #usages = Meter.detailed_predicted_usage_by_time date_ranges, dtps, meters
    render :json => usages

    #redirect_to action: 'index'
  end


# Calls the meter.usage instance method
  def single_usage
    meter = get_meters[3]
    date_ranges = get_date_ranges
    dtps = Meter.get_daily_time_periods [meter]

#    usage = meter.usage_by_meter(date_ranges, dtps)
#    usage = meter.usage_by_time(date_ranges, dtps)
    usage = meter.detailed_usage_by_meter(date_ranges, dtps)
#    usage = meter.detailed_usage_by_time(date_ranges, dtps)

    render :json => usage

#    redirect_to action: 'index'
  end

# Calls the meter.usage instance method
  def single_predicted_usage
    meter = get_meters[3]
    date_ranges = get_date_ranges
    dtps = Meter.get_daily_time_periods [meter]

#    usage = meter.predicted_usage_by_meter(date_ranges, dtps)
#    usage = meter.predicted_usage_by_time(date_ranges, dtps)
#    usage = meter.detailed_predicted_usage_by_meter(date_ranges, dtps)
    usage = meter.detailed_predicted_usage_by_time(date_ranges, dtps)

    render :json => usage

#    redirect_to action: 'index'
  end












# Empty the Records table, restart the index
  def truncate
    truncate_records
    redirect_to action: 'index'
  end

  def truncate_records
    sql = "TRUNCATE TABLE meter_records RESTART IDENTITY;"
    result = ActiveRecord::Base.connection.raw_connection.exec sql
  end

  def truncate_aggregations
    sql = "TRUNCATE TABLE meter_aggregations RESTART IDENTITY;"
    result = ActiveRecord::Base.connection.raw_connection.exec sql
  end

  # GET /meter_records
  # GET /meter_records.json
  def index
    @meter_records = MeterRecord.all
  end

  # GET /meter_records/1
  # GET /meter_records/1.json
  def show
  end

  # GET /meter_records/new
  def new
    @meter_record = MeterRecord.new
  end

  # GET /meter_records/1/edit
  def edit
  end

  # POST /meter_records
  # POST /meter_records.json
  def create
    @meter_record = MeterRecord.new(meter_record_params)

    respond_to do |format|
      if @meter_record.save
        format.html { redirect_to @meter_record, notice: 'Meter record was successfully created.' }
        format.json { render :show, status: :created, location: @meter_record }
      else
        format.html { render :new }
        format.json { render json: @meter_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meter_records/1
  # PATCH/PUT /meter_records/1.json
  def update
    respond_to do |format|
      if @meter_record.update(meter_record_params)
        format.html { redirect_to @meter_record, notice: 'Meter record was successfully updated.' }
        format.json { render :show, status: :ok, location: @meter_record }
      else
        format.html { render :edit }
        format.json { render json: @meter_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meter_records/1
  # DELETE /meter_records/1.json
  def destroy
    @meter_record.destroy
    respond_to do |format|
      format.html { redirect_to meter_records_url, notice: 'Meter record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meter_record
      @meter_record = MeterRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meter_record_params
      params.require(:meter_record).permit(:index)
    end
end

app/helpers/meter_records_helper.rb
module MeterRecordsHelper
end

app/views/meter_records/_form.html.erb
<%= form_for(@meter_record) do |f| %>
  <% if @meter_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meter_record.errors.count, "error") %> prohibited this meter_record from being saved:</h2>

      <ul>
      <% @meter_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %><br>
    <%= f.text_field :index %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meter_records/edit.html.erb
<h1>Editing Meter Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @meter_record %> |
<%= link_to 'Back', meter_records_path %>

app/views/meter_records/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">Listing Meter Records</h1>
  </div>
</div>


<%= link_to 'Import', meter_records_import_path %>&nbsp;&nbsp;
<%= link_to 'Truncate', meter_records_truncate_path %>&nbsp;&nbsp;
<%= link_to 'Multiple Meter Usage', meter_records_multiple_usage_path %>&nbsp;&nbsp;
<%= link_to 'Single Meter Usage', meter_records_single_usage_path %>&nbsp;&nbsp;
<%= link_to 'Multiple Meter Predicted Usage', meter_records_multiple_predicted_usage_path %>&nbsp;&nbsp;
<%= link_to 'Single Meter Predicted Usage', meter_records_single_predicted_usage_path %><br /><br />
<%=@meter_records.length%> Records<br /><br />
<table>
  <thead>
    <tr>
      <th>Meter&nbsp;&nbsp;</th>
      <th>Register&nbsp;&nbsp;</th>
      <th>Date&nbsp;&nbsp;</th>
      <th>Interval&nbsp;&nbsp;</th>
      <th>UOM&nbsp;&nbsp;</th>
      <th>Usage</th>
    </tr>
  </thead>

  <tbody>
    <% @meter_records.each do |meter_record| %>
      <tr>
        <td><%= meter_record.meter_id %></td>
        <td><%= meter_record.register %></td>
        <td><%= meter_record.date %></td>
        <td><%= meter_record.interval %></td>
        <td><%= meter_record.unit_of_measurement %></td>
        <td><%= meter_record.usage %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Import', meter_records_import_path %>&nbsp;&nbsp;
<%= link_to 'Truncate', meter_records_truncate_path %>&nbsp;&nbsp;
<%= link_to 'Multiple Meter Usage', meter_records_multiple_usage_path %>&nbsp;&nbsp;
<%= link_to 'Single Meter Usage', meter_records_single_usage_path %>&nbsp;&nbsp;
<%= link_to 'Multiple Meter Predicted Usage', meter_records_multiple_predicted_usage_path %>&nbsp;&nbsp;
<%= link_to 'Single Meter Predicted Usage', meter_records_single_predicted_usage_path %><br /><br />

app/views/meter_records/new.html.erb
<h1>New Meter Record</h1>

<%= render 'form' %>

<%= link_to 'Back', meter_records_path %>

app/views/meter_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @meter_record.index %>
</p>

<%= link_to 'Edit', edit_meter_record_path(@meter_record) %> |
<%= link_to 'Back', meter_records_path %>