config/routes.rb
Rails.application.routes.draw do

  root to: 'dashing#dashboard'
  get 'dashing/dashboard'
  get 'billing_sites/:id/predictions' => 'billing_sites#show_predict_usage', as: :show_predictions_billing_site
  get 'billing_sites/:id/usage' => 'billing_sites#show_usage', as: :show_usage_billing_site
  post 'billing_sites/:id/usage' => 'billing_sites#show_usage'
  resources :ftp_servers


  # nested resources for testing purpose
  scope shallow_prefix: "billing_site" do
    resources :billing_sites do
      resources :retail_plans, shallow: true
    end
  end

#  resources :billing_sites

  resources :sites
  devise_for :users, controllers: { registrations: "users/registrations" }
  get 'users/import' => 'users#upload_nem12'
  post 'users/import' => 'users#import_nem12'
  # user's show page
  get 'users/:id' => 'users#show', as: 'user', constraints: { id: /\d+/ }

  # resources :users, only: [:show],
  get 'users/profile' => 'users#show'

  resources :meters, except: [:new, :index, :show, :edit]

  # If no route matches for show, index, edit page
  get '/meters' => 'application#redirect_user'
  get '/meters/:id' => 'application#redirect_user'
  get '/meters/:id/edit' => 'application#redirect_user'

  # resources :retail_plans do
  #   collection do
  #     get :edit
  #   end
  # end

  resources :invoices do
    collection do
      get :predictNew
      post :select_date_period
      post :predict, to: "invoices#create_predicted_invoice"
      get :generateNew
      post :generate, to: "invoices#create_generated_invoice"
      get :import_invoice
      post :import, to: "invoices#create_imported_invoice"
      post :compare
    end
  end

  get 'meter_records/truncate' => 'meter_records#truncate'
  get 'meter_records/import' => 'meter_records#import_nem12'
  get 'meter_records/single_usage' => 'meter_records#single_usage'
  get 'meter_records/multiple_usage' => 'meter_records#multiple_usage'
  get 'meter_records/single_predicted_usage' => 'meter_records#single_predicted_usage'
  get 'meter_records/multiple_predicted_usage' => 'meter_records#multiple_predicted_usage'

  get 'meter_aggregations/truncate' => 'meter_aggregations#truncate'

  resources :meter_records, :meter_aggregations

  # duplicated resources
  # resources :meters

  post '/billing_sites/:id' => 'billing_sites#show'

end

app/models/ftp_server.rb
class FtpServer < ActiveRecord::Base
  belongs_to :user
  enum poll_unit: [ :days, :weeks, :months ]  # Set the Enum type for the poll_unit

  validate :name_presence

  def name_presence
    if name.blank?
      errors.add(:name,"Cannot be blank")
    end

    if server.blank?
      errors.add(:server,"Cannot be blank")
    end
  end

  ##
  # Update the last poll date and next poll date
  #
  # ==== Attributes
  #
  # * +server+ - The server instance
  #
  def self.update_poll_dates server
    server.last_poll = Date.today
    case server.poll_unit
      when "days"
        server.next_poll += server.poll_value.days
      when "weeks"
        server.next_poll += server.poll_value.weeks
      when "months"
        server.next_poll += server.poll_value.months
    end
    server.save
  end

  # Download the data from all the FTP server
  #
  def self.download
    # import the ftp support
    puts "Start running"
    require 'net/ftp'
    servers = FtpServer.where("next_poll <= ?", Date.today)
    if !servers.nil?
      servers.each do |server|
        # deal with the servers which next poll date is today
        if server.next_poll == Date.today
          # get the information of the server
          host = server.server
          username = server.username
          password = server.password
          user = server.user.name
          current_time = Time.now.to_i.to_s
          ftp = Net::FTP.new
          # connect the server
          ftp.connect(host,21)
          # login with username and password
          ftp.login(username,password)
          ftp.passive = true
          # open the directory
          ftp.chdir("FTP/")
          # Returns an array of filenames in the remote directory.
          filenames = ftp.nlst("*.csv")
          puts filenames
          FileUtils.mkdir_p "homes/#{user}/#{host}/#{current_time}"
          puts "Create directory successful"
          #Loop by value
          filenames.each do |remote_file| #Loop through each element of the array
            if ftp.mtime(remote_file) > server.last_poll
              local_file = File.join("homes/#{user}/#{host}/#{current_time}", remote_file)
              # copy the file from remote to local
              ftp.getbinaryfile(remote_file,local_file) #Get the file
              # call import_nem12 function in meter model to store the data in file
              Meter.import_nem12(File.dirname(local_file), server.user.meters.to_a)
            end
          end
          puts "File download successful"
          ftp.close
          # update the poll date
          update_poll_dates server
        end
      end
    end
  end
end

app/controllers/ftp_servers_controller.rb
class FtpServersController < ApplicationController
  before_action :set_ftp_server, only: [:show, :edit, :update, :destroy]
  layout false, only: [:new, :edit]
  # GET /ftp_servers
  # GET /ftp_servers.json
  def index
    # show the current user's ftp_server list
    @ftp_servers = current_user.ftp_servers.all
    @ftp_server = FtpServer.new
  end

  # GET /ftp_servers/1
  # GET /ftp_servers/1.json
  def show
  end

  # GET /ftp_servers/new
  def new
    @ftp_server = FtpServer.new
  end

  # GET /ftp_servers/1/edit
  def edit
  end

  # POST /ftp_servers
  # POST /ftp_servers.json
  def create
    @ftp_server = FtpServer.new(ftp_server_params)
    respond_to do |format|
      if @ftp_server.save
        format.html { redirect_to ftp_servers_url, notice: 'Ftp server was successfully created.' }
        format.json { render :show, status: :created, location: @ftp_server }
      else
        format.html { render :new }
        format.json { render json: @ftp_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ftp_servers/1
  # PATCH/PUT /ftp_servers/1.json
  def update
    respond_to do |format|
      if @ftp_server.update(ftp_server_params)
        format.html { redirect_to @ftp_server, notice: 'Ftp server was successfully updated.' }
        format.json { render :index, status: :ok, location: @ftp_server }
      else
        format.html { render :edit }
        format.json { render json: @ftp_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ftp_servers/1
  # DELETE /ftp_servers/1.json
  def destroy
    @ftp_server.destroy
    respond_to do |format|
      format.html { redirect_to ftp_servers_url, notice: 'Ftp server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ftp_server
      @ftp_server = FtpServer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ftp_server_params
      params.require(:ftp_server).permit(:name, :server, :username, :password, :last_poll, :next_poll, :poll_unit, :poll_value, :user_id)
    end
end

app/helpers/ftp_servers_helper.rb
module FtpServersHelper
end

app/views/ftp_servers/_form.html.erb
<%= bootstrap_form_for(@ftp_server) do |f| %>
  <% if @ftp_server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ftp_server.errors.count, "error") %> prohibited this ftp_server from being saved:</h2>

      <ul>
      <% @ftp_server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.text_field :server %>
  </div>
  <div class="field">
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.password_field :password %>
  </div>
  <div style="display: none;">
    <%= f.date_select :last_poll, :default => Date.today, :type => "hidden" %>
  </div>
  <div class="field">
    <%= f.date_select :next_poll %>
  </div>
  <div class="field">
    <%= f.number_field :poll_value %>
    <%= f.select :poll_unit, FtpServer.poll_units.keys, { label: "Look for new data every:" }%>
  </div>
  <div class="modal-footer">
    <div class="actions">
      <%= f.submit :class =>"btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/ftp_servers/edit.html.erb
<div class="modal-body">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <h1>Editing Ftp Server</h1>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/ftp_servers/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <!-- <ol class="breadcrumb">
        <li><%#= link_to "Home", root_path %> </li>
        <li class="active">Ftp Server</li>
      </ol> -->
      <div class="pull-right">
        <!--<a data-toggle="modal" class="btn btn-primary pull-right" data-target=".bs-example-modal-sm">New Ftp Server</a>-->
        <%= link_to "New Ftp Server", new_ftp_server_path, :class => "btn btn-primary", "data-toggle" => "modal", "data-target" => ".bs-example-modal-sm" %>
      </div>

      <h1>Ftp Server</h1>
    </div>
  </div>
  <div class="col-md-3">

  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Name</th>
              <th>Server</th>
              <th>Username</th>
              <th>Password</th>
              <th>Last poll</th>
              <th>Next poll</th>
              <th>Poll unit</th>
              <th>Poll value</th>
              <th>User</th>
              <th colspan="3"></th>
            </tr>
            </thead>

            <tbody>
            <% @ftp_servers.each do |ftp_server| %>
                <tr>
                  <td><%= link_to ftp_server.name, ftp_server %></td>
                  <td><%= ftp_server.server %></td>
                  <td><%= ftp_server.username %></td>
                  <td><%= ftp_server.password %></td>
                  <td><%= ftp_server.last_poll %></td>
                  <td><%= ftp_server.next_poll %></td>
                  <td><%= ftp_server.poll_unit %></td>
                  <td><%= ftp_server.poll_value %></td>
                  <td><%= ftp_server.user_id %></td>
                  <!--<td><%= link_to 'Show', ftp_server %></td>-->
                  <td>
                    <%= link_to "Edit", edit_ftp_server_path(ftp_server), :class => "btn btn-success btn-xs", "data-toggle" => "modal", "data-target" => ".bs-example-modal-sm" %>
                  </td>
                  <td><%= link_to 'Destroy', ftp_server, method: :delete, data: {confirm: 'Are you sure?'},:class=>"btn btn-danger btn-xs" %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<%# The modal block %>
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>


app/views/ftp_servers/new.html.erb
<div class="modal-body">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <h1>New Ftp Server</h1>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/ftp_servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ftp_server.name %>
</p>

<p>
  <strong>Server:</strong>
  <%= @ftp_server.server %>
</p>

<p>
  <strong>Username:</strong>
  <%= @ftp_server.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @ftp_server.password %>
</p>

<p>
  <strong>Last poll:</strong>
  <%= @ftp_server.last_poll %>
</p>

<p>
  <strong>Next poll:</strong>
  <%= @ftp_server.next_poll %>
</p>

<p>
  <strong>Poll unit:</strong>
  <%= @ftp_server.poll_unit %>
</p>

<p>
  <strong>Poll value:</strong>
  <%= @ftp_server.poll_value %>
</p>

<p>
  <strong>User:</strong>
  <%= @ftp_server.user_id %>
</p>

<%= link_to 'Edit', edit_ftp_server_path(@ftp_server) %> |
<%= link_to 'Back', ftp_servers_path %>