Protoype/PostGreSQLPrototype/config/routes.rb
Rails.application.routes.draw do
  resources :billings
  resources :participants
  resources :meter_aggregations
  resources :meter_records
  resources :meters

  root 'application#index'

  post '/' => 'application#index'

  match "*path", to: "application#index", via: :all

end

Protoype/PostGreSQLPrototype/app/models/meter.rb
class Meter < ActiveRecord::Base
  self.primary_key = :serial


end

Protoype/PostGreSQLPrototype/app/controllers/meters_controller.rb
class MetersController < ApplicationController
  before_action :set_meter, only: [:show, :edit, :update, :destroy]

  # GET /meters
  # GET /meters.json
  def index
    @meters = Meter.all
  end



  # GET /meters/1
  # GET /meters/1.json
  def show

  end

  # GET /meters/new
  def new
    @meter = Meter.new
  end

  # GET /meters/1/edit
  def edit
  end

  # POST /meters
  # POST /meters.json
  def create
    @meter = Meter.new(meter_params)

    respond_to do |format|
      if @meter.save
        format.html { redirect_to @meter, notice: 'Meter was successfully created.' }
        format.json { render :show, status: :created, location: @meter }
      else
        format.html { render :new }
        format.json { render json: @meter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meters/1
  # PATCH/PUT /meters/1.json
  def update
    respond_to do |format|
      if @meter.update(meter_params)
        format.html { redirect_to @meter, notice: 'Meter was successfully updated.' }
        format.json { render :show, status: :ok, location: @meter }
      else
        format.html { render :edit }
        format.json { render json: @meter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meters/1
  # DELETE /meters/1.json
  def destroy
    @meter.destroy
    respond_to do |format|
      format.html { redirect_to meters_url, notice: 'Meter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meter
      @meter = Meter.find(params[:serial])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meter_params
      params[:meter]
    end

end

Protoype/PostGreSQLPrototype/app/helpers/meters_helper.rb
module MetersHelper
end

Protoype/PostGreSQLPrototype/app/views/meters/_form.html.erb
<%= form_for(@meter) do |f| %>
  <% if @meter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meter.errors.count, "error") %> prohibited this meter from being saved:</h2>

      <ul>
      <% @meter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Protoype/PostGreSQLPrototype/app/views/meters/edit.html.erb
<h1>Editing Meter</h1>

<%= render 'form' %>

<%= link_to 'Show', @meter %> |
<%= link_to 'Back', meters_path %>

Protoype/PostGreSQLPrototype/app/views/meters/index.html.erb
<% content_for :title, "STEAM - Meters" %>
<p id="notice"><%= notice %></p>

<h1>STEAM - Meters</h1>

<table>
  <thead>
    <tr>
      <th>NMI</th>
      <th>Serial</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @meters.each do |meter| %>
      <tr>
        <td><%= meter.nmi %></td>
        <td><%= meter.serial %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Protoype/PostGreSQLPrototype/app/views/meters/new.html.erb
<h1>New Meter</h1>

<%= render 'form' %>

<%= link_to 'Back', meters_path %>

Protoype/PostGreSQLPrototype/app/views/meters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_meter_path(@meter) %> |
<%= link_to 'Back', meters_path %>